name: Go
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: golang:1.20
      env:
        GOPATH: /__w/AdamShannag/go/
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/AdamShannag/jot

    - name: Test
      run: |
        go test -cover $(go list ./... | grep -v /vendor/)
